version: "3.1"
services:
  preprod:
    build: 
      context: .
      args:
        - ENV=preprod
        - CATALINA_HOME=/usr/local/tomcat
    container_name: ecf-arcadia-back-preprod
    volumes:
      - ecf-garage-volume-dev:/usr/local/tomcat/webapps/ROOT/images
    ports:
      - 8080:8080
volumes:
  ecf-garage-volume-dev:
