version: "3.1"
services:
  back:
    build: 
      context: .
    env_file: ./env.demo.properties
    volumes:
      - ecf-arcadia-tomcat-demo:/usr/local/images
    ports:
      - 8083:8080
    depends_on:
      - postgres
      - mongodb

  postgres:
    image: postgres:14-alpine
    env_file: ./env.demo.properties
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ecf-arcadia-postgres-demo:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d

  mongodb:
    image: mongo:8.0.0-rc8-jammy
    env_file: ./env.demo.properties
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ecf-arcadia-mongodb-demo:/etc/mongo
      - ./mongodb:/docker-entrypoint-initdb.d

volumes:
  ecf-arcadia-tomcat-demo:
  ecf-arcadia-postgres-demo:
  ecf-arcadia-mongodb-demo:
