# version: "3.1"
# services:
#   tomcat-ecf-arcadia:
#     # container_name: symfony-build
#     build: 
#       context: .
#       dockerfile: Dockerfile    
#     volumes:
#       - ./:/usr/local/tomcat/webapps
