version: "3.1"
services:
  back:
    build: 
      context: .
      args:
        - ENV=preprod
        - CATALINA_HOME=/usr/local/tomcat
    env_file: src/main/resources/preprod/env.properties
    volumes:
      - ecf-arcadia-tomcat-preprod:/usr/local/tomcat/webapps/ROOT/images
    ports:
      - 8082:8080
    depends_on:
      - postgres
      - mongodb

  postgres:
    image: postgres:14-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ecf-arcadia-postgres-preprod:/var/lib/postgresql/data

  mongodb:
    image: mongo:8.0.0-rc8-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ecf-arcadia-mongodb-preprod:/etc/mongo

volumes:
  ecf-arcadia-tomcat-preprod:
  ecf-arcadia-postgres-preprod:
  ecf-arcadia-mongodb-preprod:
