version: "3.1"
services:
  preprod:
    image: ecf-arcadia-back
    # build: 
    #   context: .
    #   args:
    #     - ENV=preprod
    #     - CATALINA_HOME=/usr/local/tomcat
    container_name: ecf-arcadia-back-preprod
    volumes:
      - ecf-garage-volume-preprod:/usr/local/tomcat/webapps/ROOT/images
      - ./src/main/resources/preprod:/usr/local/tomcat/lib
    ports:
      - 8080:8080

  test:
    image: ecf-arcadia-back
    # build: 
    #   context: .
    #   args:
    #     - ENV=test
    #     - CATALINA_HOME=/usr/local/tomcat
    container_name: ecf-arcadia-back-test
    volumes:
      - ecf-garage-volume-test:/usr/local/tomcat/webapps/ROOT/images
    ports:
      - 8082:8080
    environment:
      - ENV=test
      - CATALINA_HOME=/usr/local/tomcat

volumes:
  ecf-garage-volume-preprod:
  ecf-garage-volume-test:
